'use strict';
exports.up = async (knex) => {
  await knex.schema.createTable('consultations', (t) => {
    t.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));
    t.uuid('appointment_id').notNullable().references('id').inTable('appointments').onDelete('RESTRICT').unique();
    t.uuid('patient_id').notNullable().references('id').inTable('patients').onDelete('RESTRICT');
    t.uuid('doctor_id').notNullable().references('id').inTable('doctors').onDelete('RESTRICT');
    t.uuid('hospital_id').notNullable().references('id').inTable('hospitals').onDelete('RESTRICT');
    t.uuid('pregnancy_id').nullable().references('id').inTable('pregnancies').onDelete('SET NULL');
    t.jsonb('vitals').nullable().defaultTo('{}');
    t.jsonb('obstetric_observations').nullable().defaultTo('{}');
    t.text('symptoms').nullable();
    t.jsonb('diagnosis_tags').nullable().defaultTo('[]');
    t.text('diagnosis_notes').nullable();
    t.text('treatment_plan').nullable();
    t.text('doctor_notes').nullable();
    t.text('high_risk_update').nullable();
    t.text('report_reviewed').nullable();
    t.text('referred_to').nullable();
    t.text('milestone_impact').nullable();
    t.specificType('consultation_outcome', 'consultation_outcome_enum').nullable();
    t.boolean('is_finalized').notNullable().defaultTo(false);
    t.timestamp('finalized_at').nullable();
    t.uuid('finalized_by').nullable().references('id').inTable('users');
    t.text('override_reason').nullable();
    t.date('consultation_date').notNullable().defaultTo(knex.raw('CURRENT_DATE'));
    t.uuid('created_by').nullable().references('id').inTable('users');
    t.timestamps(true, true);
  });
  await knex.raw('CREATE INDEX idx_consultations_hospital_id ON consultations(hospital_id)');
  await knex.raw('CREATE INDEX idx_consultations_patient_id ON consultations(patient_id)');
};
exports.down = (knex) => knex.schema.dropTableIfExists('consultations');
