'use strict';
exports.up = async (knex) => {
  await knex.schema.createTable('invoices', (t) => {
    t.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));
    t.uuid('hospital_id').notNullable().references('id').inTable('hospitals').onDelete('RESTRICT');
    t.uuid('branch_id').nullable().references('id').inTable('branches').onDelete('SET NULL');
    t.uuid('patient_id').notNullable().references('id').inTable('patients').onDelete('RESTRICT');
    t.uuid('consultation_id').nullable().references('id').inTable('consultations').onDelete('SET NULL');
    t.string('invoice_number', 30).nullable();
    t.specificType('status', 'invoice_status_enum').notNullable().defaultTo('draft');
    t.decimal('subtotal', 10, 2).notNullable().defaultTo(0);
    t.decimal('discount_amount', 10, 2).notNullable().defaultTo(0);
    t.decimal('tax_amount', 10, 2).notNullable().defaultTo(0);
    t.decimal('total_amount', 10, 2).notNullable().defaultTo(0);
    t.decimal('paid_amount', 10, 2).notNullable().defaultTo(0);
    t.boolean('discount_approval_required').notNullable().defaultTo(false);
    t.uuid('discount_approved_by').nullable().references('id').inTable('users');
    t.text('notes').nullable();
    t.text('void_reason').nullable();
    t.uuid('voided_by').nullable().references('id').inTable('users');
    t.timestamp('voided_at').nullable();
    t.uuid('created_by').notNullable().references('id').inTable('users');
    t.boolean('is_deleted').notNullable().defaultTo(false);
    t.timestamp('deleted_at').nullable();
    t.uuid('deleted_by').nullable().references('id').inTable('users');
    t.timestamps(true, true);
  });
  await knex.raw('CREATE INDEX idx_invoices_hospital_id ON invoices(hospital_id)');
  await knex.raw('CREATE INDEX idx_invoices_patient_id ON invoices(patient_id)');
  await knex.raw('CREATE UNIQUE INDEX idx_invoices_number ON invoices(hospital_id, invoice_number) WHERE invoice_number IS NOT NULL');
};
exports.down = (knex) => knex.schema.dropTableIfExists('invoices');
