'use strict';
exports.up = async (knex) => {
  await knex.schema.createTable('patient_documents', (t) => {
    t.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));
    t.uuid('patient_id').notNullable().references('id').inTable('patients').onDelete('RESTRICT');
    t.uuid('hospital_id').notNullable().references('id').inTable('hospitals').onDelete('RESTRICT');
    t.uuid('pregnancy_id').nullable().references('id').inTable('pregnancies').onDelete('SET NULL');
    t.uuid('consultation_id').nullable().references('id').inTable('consultations').onDelete('SET NULL');
    t.uuid('linked_test_order_id').nullable().references('id').inTable('patient_test_orders').onDelete('SET NULL');
    t.specificType('document_type', 'document_type_enum').notNullable();
    t.text('s3_key').notNullable();
    t.string('file_name', 500).notNullable();
    t.string('mime_type', 100).notNullable();
    t.integer('file_size_bytes').nullable();
    t.integer('file_size_kb').nullable();
    t.uuid('uploaded_by').nullable().references('id').inTable('users').onDelete('SET NULL');
    t.timestamp('uploaded_at').notNullable().defaultTo(knex.raw('NOW()'));
    t.string('lab_name', 200).nullable();
    t.date('test_date').nullable();
    t.specificType('review_status', 'doc_review_status_enum').notNullable().defaultTo('pending_review');
    t.uuid('reviewed_by').nullable().references('id').inTable('users').onDelete('SET NULL');
    t.timestamp('reviewed_at').nullable();
    t.boolean('abnormal_flag').notNullable().defaultTo(false);
    t.text('review_notes').nullable();
    t.jsonb('extracted_key_values').nullable();
    t.boolean('is_deleted').notNullable().defaultTo(false);
    t.uuid('deleted_by').nullable().references('id').inTable('users').onDelete('SET NULL');
    t.timestamp('deleted_at').nullable();
    t.text('deleted_reason').nullable();
    t.timestamps(true, true);
  });
  await knex.raw('CREATE INDEX idx_patient_documents_hospital_id ON patient_documents(hospital_id)');
  await knex.raw('CREATE INDEX idx_patient_documents_patient_id ON patient_documents(patient_id)');
  await knex.raw('CREATE INDEX idx_patient_documents_review_status ON patient_documents(review_status)');
};
exports.down = (knex) => knex.schema.dropTableIfExists('patient_documents');
