export * from './patient.enums.js'
export * from './appointment.enums.js'
export * from './consultation.enums.js'
export * from './pregnancy.enums.js'
export * from './prescription.enums.js'
export * from './testDocument.enums.js'
export * from './billing.enums.js'
